name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      # Write permission is required to create a github release
      contents: write
      # Write permission is required for autolabeler
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
